# Generated by Django 4.0.6 on 2022-08-19 21:57

from django.db import migrations, models
import photos.validators
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=users.models.rename_profile_pic, validators=[photos.validators.file_size_validator]),
        ),
    ]
