# Generated by Django 4.0.6 on 2022-09-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='summary_email',
            field=models.BooleanField(default=False),
        ),
    ]
