# Generated by Django 4.0.6 on 2022-08-19 21:57

from django.db import migrations, models
import photos.models
import photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_slug_alter_photo_image_alter_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=photos.models.rename_uploaded_photo, validators=[photos.validators.file_size_validator]),
        ),
    ]
